---
fixtures:
  forge_modules:
    acl: "puppetlabs/acl"
    chocolatey: "puppetlabs/chocolatey"
    concat: "puppetlabs/concat"
    cygwin: "mdelaney/cygwin"
    node_encrypt: "binford2k/node_encrypt"
    registry: "puppetlabs/registry"
    stdlib: "puppetlabs/stdlib"
    windows_env: "puppet/windows_env"
